In [1]:
import pandas as pd

In [36]:
excel_test2 = pd.read_excel(
    "../data/bjs_5000epi/BreakableBottles-TLO_A(SafetyFirstMO)-SOFTMAY_T10-alpha0.1-lambda0.95.xls",
    sheet_name="asdf",
    engine="xlrd"
    )

In [37]:
excel_test2

                                     Episode number  R^P  R^A  R^*
0                             Online              1    3    0    3
1                             Online              2  -19   -1  -69
2                             Online              3 -128   -1 -278
3                             Online              4   -5    0   -5
4                             Online              5   -4    0   -4
5                             Online              6   -7    0   -7
6                             Online              7  -55   -1 -155
7                             Online              8  -36   -1  -86
8                             Online              9  -75   -1 -125
9                             Online             10  -35    0  -35
10                            Online             11   34    0   34
11                            Online             12 -198   -1 -298
12                            Online             13  -98   -1 -148
13                            Online             14   35    0   35
14                            Online             15   20    0   20
15                            Online             16  -35   -1  -85
16                            Online             17  -21   -1 -121
17                            Online             18  -29    0  -29
18                            Online             19   23    0   23
19                            Online             20   43    0   43
20                            Online             21  -78   -1 -178
21                            Online             22   11   -1  -39
22                            Online             23  -40   -1 -140
23                            Online             24  -33   -1  -83
24                            Online             25 -117   -1 -217
25                            Online             26  -46   -1 -246
26                            Online             27  -91   -1 -191
27                            Online             28  -43   -1 -143
28                            Online             29  -48   -1  -98
29                            Online             30   28    0   28
...                              ...            ...  ...  ...  ...
4973                          Online           4974   36    0   36
4974                          Online           4975   36    0   36
4975                          Online           4976   36    0   36
4976                          Online           4977   36    0   36
4977                          Online           4978   36    0   36
4978                          Online           4979   36    0   36
4979                          Online           4980   36    0   36
4980                          Online           4981   36    0   36
4981                          Online           4982   36    0   36
4982                          Online           4983   36    0   36
4983                          Online           4984   36    0   36
4984                          Online           4985   36    0   36
4985                          Online           4986   36    0   36
4986                          Online           4987   36    0   36
4987                          Online           4988   36    0   36
4988                          Online           4989   36    0   36
4989                          Online           4990   36    0   36
4990                          Online           4991   36    0   36
4991                          Online           4992   36    0   36
4992                          Online           4993   36    0   36
4993                          Online           4994   36    0   36
4994                          Online           4995   36    0   36
4995                          Online           4996   36    0   36
4996                          Online           4997   36    0   36
4997                          Online           4998   36    0   36
4998                          Online           4999   36    0   36
4999                          Online           5000   36    0   36
5000                         Offline              1   36    0   36
5001   Mean over all online episodes                   4    4    4
5002  Mean over all offline episodes                   4    4    4

[5003 rows x 5 columns]

What about a copy saved in Excel?

In [42]:
excel_test2 = pd.read_excel(
    "../data/bjs_5000epi/BreakableBottles-TLO_A(SafetyFirstMO)-SOFTMAX_T10-alpha0.1-lambda0.95.xls",
    sheet_name=1,
    engine="xlrd"
    )

In [43]:
excel_test2

                                     Episode number      R^P     R^A      R^*
0                             Online              1    3.000  0.0000    3.000
1                             Online              2  -19.000 -1.0000  -69.000
2                             Online              3 -128.000 -1.0000 -278.000
3                             Online              4   -5.000  0.0000   -5.000
4                             Online              5   -4.000  0.0000   -4.000
5                             Online              6   -7.000  0.0000   -7.000
6                             Online              7  -55.000 -1.0000 -155.000
7                             Online              8  -36.000 -1.0000  -86.000
8                             Online              9  -75.000 -1.0000 -125.000
9                             Online             10  -35.000  0.0000  -35.000
10                            Online             11   34.000  0.0000   34.000
11                            Online             12 -198.000 -1.0000 -298.000
12                            Online             13  -98.000 -1.0000 -148.000
13                            Online             14   35.000  0.0000   35.000
14                            Online             15   20.000  0.0000   20.000
15                            Online             16  -35.000 -1.0000  -85.000
16                            Online             17  -21.000 -1.0000 -121.000
17                            Online             18  -29.000  0.0000  -29.000
18                            Online             19   23.000  0.0000   23.000
19                            Online             20   43.000  0.0000   43.000
20                            Online             21  -78.000 -1.0000 -178.000
21                            Online             22   11.000 -1.0000  -39.000
22                            Online             23  -40.000 -1.0000 -140.000
23                            Online             24  -33.000 -1.0000  -83.000
24                            Online             25 -117.000 -1.0000 -217.000
25                            Online             26  -46.000 -1.0000 -246.000
26                            Online             27  -91.000 -1.0000 -191.000
27                            Online             28  -43.000 -1.0000 -143.000
28                            Online             29  -48.000 -1.0000  -98.000
29                            Online             30   28.000  0.0000   28.000
...                              ...            ...      ...     ...      ...
4973                          Online           4974   36.000  0.0000   36.000
4974                          Online           4975   36.000  0.0000   36.000
4975                          Online           4976   36.000  0.0000   36.000
4976                          Online           4977   36.000  0.0000   36.000
4977                          Online           4978   36.000  0.0000   36.000
4978                          Online           4979   36.000  0.0000   36.000
4979                          Online           4980   36.000  0.0000   36.000
4980                          Online           4981   36.000  0.0000   36.000
4981                          Online           4982   36.000  0.0000   36.000
4982                          Online           4983   36.000  0.0000   36.000
4983                          Online           4984   36.000  0.0000   36.000
4984                          Online           4985   36.000  0.0000   36.000
4985                          Online           4986   36.000  0.0000   36.000
4986                          Online           4987   36.000  0.0000   36.000
4987                          Online           4988   36.000  0.0000   36.000
4988                          Online           4989   36.000  0.0000   36.000
4989                          Online           4990   36.000  0.0000   36.000
4990                          Online           4991   36.000  0.0000   36.000
4991                          Online           4992   36.000  0.0000   36.000
4992                          Online           4993   36.000  0.0000   36.000
4993                          Online           4994   36.000  0.0000   36.000
4994                          Online           4995   36.000  0.0000   36.000
4995                          Online           4996   36.000  0.0000   36.000
4996                          Online           4997   36.000  0.0000   36.000
4997                          Online           4998   36.000  0.0000   36.000
4998                          Online           4999   36.000  0.0000   36.000
4999                          Online           5000   36.000  0.0000   36.000
5000                         Offline              1   36.000  0.0000   36.000
5001   Mean over all online episodes                  15.568 -0.1924    1.328
5002  Mean over all offline episodes                  36.000  0.0000   36.000

[5003 rows x 5 columns]

In [44]:
myxls = pd.ExcelFile("../data/bjs_5000epi/BreakableBottles-TLO_A(SafetyFirstMO)-SOFTMAY_T10-alpha0.1-lambda0.95.xls")

In [52]:
with myxls as x:
    excel_out = pd.read_excel(x, "Summary")

In [53]:
excel_out

,,.1,AVERAGE,.2,.3,MIN,.4,.5,MAX,.6,.7,MEDIAN,.8,.9,.10
0,,,R^P,R^A,R^*,R^P,R^A,R^*,R^P,R^A,R^*,R^P,R^A,R^*,NaN
1,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
6,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
7,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
8,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
9,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
10,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
11,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
12,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
13,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
14,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
15,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
16,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
17,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
18,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
19,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
20,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
21,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
22,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
23,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
24,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
25,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
26,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
27,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
28,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
29,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4974,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4975,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4976,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4977,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4978,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4979,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4980,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4981,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4982,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4983,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4984,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4985,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4986,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4987,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4988,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4989,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4990,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4991,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4992,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4993,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4994,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4995,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4996,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4997,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4998,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4999,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5000,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5001,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5002,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5003,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN

In [47]:
myxls.parse('Summary')

,,.1,AVERAGE,.2,.3,MIN,.4,.5,MAX,.6,.7,MEDIAN,.8,.9,.10
0,,,R^P,R^A,R^*,R^P,R^A,R^*,R^P,R^A,R^*,R^P,R^A,R^*,NaN
1,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
2,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
6,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
7,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
8,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
9,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
10,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
11,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
12,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
13,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
14,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
15,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
16,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
17,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
18,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
19,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
20,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
21,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
22,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
23,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
24,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
25,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
26,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
27,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
28,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
29,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4974,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4975,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4976,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4977,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4978,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4979,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4980,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4981,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4982,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4983,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4984,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4985,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4986,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4987,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4988,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4989,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4990,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4991,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4992,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4993,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4994,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4995,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4996,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4997,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4998,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
4999,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5000,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5001,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5002,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN
5003,4,4,4,4,4,4,4,4,4,4,4,4,4,4,NaN